### ISSUE TITLE
Error in checkForRemoteErrors(val): one node produced an error: replacement has length zero

### ISSUE THREAD

**Issue by tianas** [collinn/bdots#22]
Hi there,

Here is the code I'm running:

```
fit <- bdotsFit(data = fit_data,
                subject = "ppt",
                time = "bin_index",
                y = "avg_fixations",
                group = "cond",
                curveType = doubleGauss2(concave=TRUE),
                cor=TRUE)
```

And I get this error message:

```
Error in checkForRemoteErrors(val) : 
  one node produced an error: replacement has length zero
```

The same code is running fine on a slightly different dataset with the same variables/conditions/values, but different binning (50 ms bins for 2000 ms time window works, but 20 ms for 1000 ms does not).

I changed the number of cores to 0, 1, and 2, and all through the same error (except `cores=1` throws that _one_ node produced an error.)

**Comment by collinn** [comment]
Without the dataset, I can't be *entirely* sure that this is the case, but based on your comment, my suspicion is that it has to do with the different time scale used. The `doubleGauss2` function was written to emulate matlab code that had better convergence properties, but iirc it had values hard coded that assumed the time window was 2000ms. From this, you might try one of three things for now:

1. Use `doubleGauss` instead of `doubleGauss2`, though you may have lower quality fits
2. Multiply your time values by 2 so that you are effectively working with 2000ms with 40ms bins, then mentally adjust back when looking at results. 
3. I haven't pushed to the dev branch in awhile, but it may have some updates that assist with the refitting step if `doubleGauss` is still pretty bad. I'm hopeful to have more updates wrapped up and merged into master by the end of the month

Let me know if any of these end up working out!

**Comment by tianas** [comment]
Thanks for your response! Unfortunately none of the options helped. When using `doubleGauss`, I get the following error message instead:

```
Error in checkForRemoteErrors(val) : 
  2 nodes produced errors; first error: object 'sig2' not found
```

I will keep trying to adjust the time values as I suspect that's the issue as well and will let you know if I find a solution!

**Comment by collinn** [comment]
Weird, I just had somebody else email with the sig2 issue over the weekend -- not quite sure what the issue with that is yet or why it's just now coming up. It might be tomorrow before I get a chance to get into it, but I'll be sure to report back as soon as I do!

**Comment by collinn** [comment]
Ok, so the similar issue that I had come up was an instance in which one of the subjects had a single unique value for the `y` variable, causing issues when estimating the variance. I haven't made an adjustment in the code yet, but you might check if a similar thing is an issue for you. 

Assuming that your dataset is called `df` and that `y`, `subject`, and `group` are character vectors associated with the `bdotsFit` function call, you might run

```
df <- as.data.table(df)
df[, length(unique(get(y))), by = c(subject, group)][V1 == 1, ]
```
to see any subject/group combinations in which all of the outcomes are the same. Let me know if this is the case and if removing them solves the issue you were having previously (though, I suspect there will still be time issues using the 1000ms time scale with `doubleGauss2`)
